https:
 host: 0.0.0.0
 port: "8082"
 
http:
 host: 0.0.0.0
 port: "8081"
 
keystore:
 password: "password"
 
password: "password"

apiid: ""
  
sfdc:
  user: ""
  pass: ""
  token: ""
  
callback:
  app: "https://cloud-carbon-footprint.us-e2.cloudhub.io"